# Generated by Django 5.2.4 on 2025-07-22 14:38

import Commandes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Articles', '0001_initial'),
        ('Clients', '0002_alter_client_options_alter_client_date_ajout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_commande', models.CharField(default=Commandes.models.generate_matricule, max_length=50, unique=True)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='Clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(max_length=200000)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_commande', to='Commandes.commande')),
            ],
        ),
    ]
