# Generated by Django 5.2.4 on 2025-07-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commandes', '0002_alter_articlecommande_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_retrait',
            field=models.DateField(blank=True, null=True),
        ),
    ]
