# Generated by Django 5.2.4 on 2025-07-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=500)),
                ('prix_unitaire', models.IntegerField(max_length=5000)),
            ],
        ),
    ]
