# Generated by Django 5.2.4 on 2025-07-20 20:59

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=500)),
                ('email', models.EmailField(default='client@Emailfield', max_length=254)),
                ('num_telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('date_ajout', models.DateField(auto_now=True)),
            ],
        ),
    ]
