# Generated by Django 5.2.4 on 2025-07-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-date_ajout',)},
        ),
        migrations.AlterField(
            model_name='client',
            name='date_ajout',
            field=models.DateField(auto_now_add=True),
        ),
    ]
