# Generated by Django 5.2.4 on 2025-07-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdmin',
        ),
    ]
